[package]
name = "quizst"
version = "0.3.2"
entrypoint = "lib.typ"
authors = ["MuhammadAly11"]
license = "MIT"
description = "Typst template for McQ exams"
exclude = ["example"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "template/thumbnail.png"
